# Site settings
title: "Roshni Reports"
description: "Data-driven insights and analytics"
baseurl: ""  # Leave empty for the root
url: "https://roshnireports.github.io"
author: "Roshni Arif"

# Use Minimal Mistakes as a remote theme
remote_theme: "mmistakes/minimal-mistakes"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate  # If you want pagination for blog posts

# Optional social links
social:
  github: https://github.com/RoshniArif
  linkedin: https://linkedin.com/in/roshniarif

# Permalinks for posts
permalink: /:categories/:title/

# Timezone
timezone: America/Los_Angeles
